### ISSUE TITLE
rset data

### ISSUE THREAD

**Issue by fachridjal** [levitnudi/LegacyTableView#2]
how to clear/ reset data row

**Comment by levitnudi** [comment]
You can re-instantiate e.g (new LegacyTableView) add your new content and and column titles, then build...

**Comment by adelhawa** [comment]
@fachridjal hey man did you find a way out because i have same issue ?

**Comment by levitnudi** [comment]
Hi, checkout the UpdateTable activity with update feature. You can now dynamically update your table data, themes, languages, fonts and colors.

make sure to add this : implementation 'com.github.levitnudi:LegacyTableView:master-SNAPSHOT'
