### ISSUE TITLE
Failed to resolve: com.github.levitnudi:LegacyTableView:master-SNAPSHOT

### ISSUE THREAD

**Issue by sumancreative** [levitnudi/LegacyTableView#7]
Suddenly I get the below error while trying to build my project

Failed to resolve: com.github.levitnudi:LegacyTableView:master-SNAPSHOT

please help

**Comment by levitnudi** [comment]
Make sure you disable offline mode on android studio then sync to download the repo. It should work. Alternatively, clear cache then sync your project.

**Comment by sumancreative** [comment]
Hi,

Sorry for late reply. offline mode on android studio is disabled and also clear the cache. but it still gives the save error. Below is the error

"Failed to resolve: com.github.levitnudi:LegacyTableView:master-SNAPSHOT"

**Comment by sarathideoder** [comment]
After updating andoid studio i got this error: **Failed to resolve: com.github.levitnudi:LegacyTableView:master-SNAPSHOT**
I think this happened when migrating to androidX

**Comment by heyjude992241** [comment]
Same here, getting the same error while syncing gradle file. Last time I used it worked well. Please help

"Failed to resolve: com.github.levitnudi:LegacyTableView:master-SNAPSHOT"

**Comment by akarmehmet** [comment]
i have the same error when i migrate to androidx

**Comment by githeyj** [comment]
Getting the  same error here

**Comment by levitnudi** [comment]
Hey guys, I'm sorry for late response. Could you try using the library folder in your build gradles? Instead of the repo, just download and import legacytableview module. It should work

**Comment by sumancreative** [comment]
Facing the same issue. Previously it works perfect, but suddenly it's not resolving .

**Comment by levitnudi** [comment]
What if you use the module instead -> replace  compile '
com.github.levitnudi:LegacyTableView:master-SNAPSHOT' with  implementation
project(':legacytableview'). Compile was replaced with Implementation in
the new build versions.


Best Regards
Levit Nudi

Seest thou a man diligent in his business? he shall stand before kings; he
shall not stand before mean men. Proverbs 22:29

Cell : +254701161136
Skype: Levit Nudi

**Comment by SGL-IGiS** [comment]
By today i faced the same issue and unable to resolve any one guide me how could i resolve it.
Thanks

**Comment by levitnudi** [comment]
Please use this version of the module, appologies for the long standing errors. Use implementation 'com.github.levitnudi:LegacyTableView:1.2' instead of implementation 'com.github.levitnudi:LegacyTableView:master-SNAPSHOT'
